export const LOADING_TOGGLE = "LOADING_TOGGLE";
export const ADD_POKEMONS = "ADD_POKEMONS";
export const ADD_DETAIL_POKEMON = "ADD_DETAIL_POKEMON";
export const ADD_MY_POKEMONS = "ADD_MY_POKEMONS";
export const ADD_MY_DETAIL_POKEMON = "ADD_MY_DETAIL_POKEMON";
export const RELEASE_MY_POKEMON = "RELEASE_MY_POKEMON";
export const RENAME_MY_POKEMON = "RENAME_MY_POKEMON";
